version: 2
jobs:
  build:
    docker:
      - image: thegreenhouse/nodejs-dev:0.4.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Debug environment
          command: node -v && npm -v && yarn -v

      - run:
          name: Install Project Dependencies
          command: npm ci

      - run:
          name: Install Project Dependencies
          command: ./node_modules/.bin/eslint *.js ./src/**/**/*.js

      - run:
          name: Run build
          command: npm run build